apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "react-nginx-aks"
    labels:
        app: "react-nginx-aks"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: ajitazure-updated-react-nginx-aks.413126a369a048389dfd.centralus.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "react-nginx-aks"
                servicePort: 8080