apiVersion: v1
kind: Service
metadata:
  name: e-load-balancer-ajitazureaks-ea0d
spec:
  type: LoadBalancer
  selector:
    app: ajitazureaks-ea0d
  ports:
  - port: 80
    targetPort: 8080
