on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ajitacr.azurecr.io
        username: ${{ secrets.acr_ajitacr_username }}
        password: ${{ secrets.acr_ajitacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/frontend" -f  "frontend/Dockerfile" -t ajitacr.azurecr.io/ajitazureaks:${{ github.sha }} --label dockerfile-path=frontend/Dockerfile
        docker push ajitacr.azurecr.io/ajitazureaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_ajitazureaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ajitazure-updated | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ajitazure-updated`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ajitazure-updated
        container-registry-url: ajitacr.azurecr.io
        container-registry-username: ${{ secrets.acr_ajitacr_username }}
        container-registry-password: ${{ secrets.acr_ajitacr_password }}
        secret-name: ajitazureaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ajitazure-updated
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          ajitacr.azurecr.io/ajitazureaks:${{ github.sha }}
        imagepullsecrets: |
          ajitazureaksdockerauth
